---

- name: Copy Comodo Installer
  template: 
    src: comodo-install.run
    dest: /tmp/comodo-install.run
    owner: root
    group: root
    mode: 0755
    
- name: Execute Comodo Installer
  command: sh /tmp/comodo-install.run
